# Generated by Django 5.0.4 on 2024-04-06 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=120)),
                ('architecture', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('ping', models.IntegerField(max_length=4)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.service')),
            ],
        ),
    ]
