# Generated by Django 5.0.4 on 2024-04-07 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_monitor_log_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor_log',
            old_name='status',
            new_name='status_code',
        ),
    ]
