# Generated by Django 5.0.4 on 2024-04-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor_log',
            name='ping',
            field=models.IntegerField(),
        ),
    ]
